### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by Sreyas-Sreelal**
* Update to latest edition
* Fix warnings in latest compiler
* Apply clippy lints
* Run rustfmt

### CODE REVIEW

**Comment by juanibiapina** [comment]
Very nice! Why not also replace `try` with `?` ?

**Comment by Sreyas-Sreelal** [comment]
done!

**Comment by juanibiapina** [comment]
Since we're here, it seems there are still 4 places where it says:

```
warning: trait objects without an explicit `dyn` are deprecated 
```

**Comment by juanibiapina** [comment]
I'll do it myself, it's faster.

**Comment by juanibiapina** [comment]
Merged! Thanks!

**Pull request merged**
